### ISSUE TITLE
Is there a way to show the progress of a song when using a SHOUTcast stream?

### ISSUE THREAD

**Issue by mischa78** [maboa/circleplayer#16]
I'm using the CirclePlayer with a SHOUTcast stream like this:

```
cp = new CirclePlayer('#jquery_jplayer_1', {},
{
  ready: function(event)
  {
    cp.player.jPlayer('setMedia', { mp3: 'http://stream-url:8004' });
  }, // Etc
}
```

This doesn't show the progress of the song. Is there a way to do that?

**Comment by kimhoo** [comment]
There's only the history of played songs with a start-marker in seconds provided. If it includes the current playing song, you could possibly use those figures combined with the provided music's meta-data (http://wiki.winamp.com/wiki/SHOUTcast_XML_Metadata_Specification) to give the song's length to calculate what the current progress is.

So combine song history data (page=4) to grab the UTC time in seconds for the currently playing song and get the songs length to calculate. In this case it is neccessary to make sure the server and client's time are always the same or you could provide a way to transport the system's current time to the client as well.

Does this help?

**Comment by mischa78** [comment]
Yes, @kimhoo, you have given me an idea. Thanks. For now I just won't show the progress, but I will look into this sometime later.
